### PR TITLE
Fix anonymous functions in hooks

### LINKED ISSUE #117: gensym / anonymous function syntax breaks fast refresh
Simple reproduction that will cause fast refresh to always do a full reload:

```clojure
(defnc ...
  (hooks/use-effect
    []
    (run-my-callback #(identity %)))
  ...)
```

It will be fixed by using `(fn [%] (identity %))` instead.  The problem is that on each reload the gensym'd binding that replaces `%` is changed.  Compare:

```clojure
(hooks/use-effect [] (reitit.frontend.easy/start! (reitit.frontend/router []) (fn* [p1__27869#] (identity p1__27869#)) {:use-fragment false})) 
;; vs
(hooks/use-effect [] (reitit.frontend.easy/start! (reitit.frontend/router []) identity {:use-fragment false}))
```

I don't have an clear idea on how to best fix this. If there was a way to detect & remove gensym'd symbols, that would be ideal.  I don't know think that's possible at all.

The anonymous function syntax seems likely to be the most common (only? is this something that can only happen from syntax, or could a macro cause it too?) cause of this and it will always end its binding with `#`, or you could pick up on the prefix of `p\d+__` for that case, too.

### PR DESCRIPTION
**Pull request by SevereOverfl0w**
Fix #117

### CODE REVIEW

File: src/helix/impl/analyzer.clj [hunk 1]
```diff
@@ -73,14 +73,23 @@ Example: ($ %s %s ...)"
...
+(defn- normalise-jsval
+  [x]
+  (if (= JSValue (type x))
+    (.-val x)
+    x))
+
+(defn- normalise-sym
+  [x]
+  (if (symbol? x)
+    (symbol (string/replace (str x) #"^((p\d+|rest))(__\d+)#$" "$1__#"))
```
Comment (lilactown) [inline src/helix/impl/analyzer.clj:85]: IIUC this string/replace takes a value like `p123__456#` and returns `p123__#`, and this works because the `pX` number is related to the place within the form. Did I get that right?

I am curious if the `pX` is local to the binding form, or to the file, or global. I could see any of them being reasonable. I think best for us would be local to the binding form, because it would mean edits to other places in the same file/project wouldn't bust the fast refresh cache. I think no matter what, this is better than what we had before!

Comment (SevereOverfl0w) [reply src/helix/impl/analyzer.clj:85]: The first number is the index of the parameter, yep. So `%` corresponds to p1, so does `%1`. `%2` corresponds to `p2` etc.

And obviously `%&` corresponds to `rest`.

So local to the function bindings.
